[package]
name = "tdkc"
version = "1.0.1"
edition = "2021"
description = "Target Distilled K-mer Classifier"

[dependencies]
clap = { version = "4", features = ["derive"] }
boomphf = { version = "0.6", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
bincode = "1"
rayon = "1"
needletail = "0.6"
anyhow = "1"
dashmap = "6"
num_cpus = "1"
rustc-hash = "2"
flate2 = { version = "1", features = ["zlib-ng"], default-features = false }
crossbeam-channel = "0.5"
itertools = "0.12"
libc = "0.2"
memmap2 = "0.9"
fastbloom = { version = "0.17", features = ["serde"] }
hyperloglogplus = "0.4"
reqwest = { version = "0.12", features = ["stream", "default-tls"], default-features = false }
async-compression = { version = "0.4", features = ["tokio", "gzip"] }
tokio-util = { version = "0.7", features = ["io"] }
async-trait = "0.1"
sha2 = "0.10"
hex = "0.4"
tar = "0.4"
futures = "0.3"
async-stream = "0.3"
memchr = "2"
tokio = { version = "1.0", features = ["full"] }
bytes = "1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1